# -*- coding: utf-8 -*-
"""Task 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dh-oZxp2Sd7NWJkGuOZ9OC0yFWTQAB90
"""

!pip install transformers torch

!pip install transformers torch

from transformers import pipeline

generator = pipeline("text-generation", model="gpt2")

prompt = "Artificial Intelligence is"

result = generator(prompt, max_length=50)

print(result[0]["generated_text"])

!pip install transformers datasets

from transformers import GPT2Tokenizer, GPT2LMHeadModel

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model = GPT2LMHeadModel.from_pretrained("gpt2")

prompt = "Machine Learning"

inputs = tokenizer(prompt, return_tensors="pt")

outputs = model.generate(
    **inputs,
    max_length=40
)

print(tokenizer.decode(outputs[0], skip_special_tokens=True))